// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnA0nYmvhMDDz7S0lHcw7ld1kr89fndl4',
    appId: '1:645002434672:web:7b33eb5d9b2f0f52a2fcb5',
    messagingSenderId: '645002434672',
    projectId: 'gigafaucet-dev',
    authDomain: 'gigafaucet-dev.firebaseapp.com',
    storageBucket: 'gigafaucet-dev.firebasestorage.app',
    measurementId: 'G-R3L5QRX91W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrNhTkizyKefk7fZhPeWZPIrEmQR2hyI',
    appId: '1:645002434672:android:7aebe7d704f45a63a2fcb5',
    messagingSenderId: '645002434672',
    projectId: 'gigafaucet-dev',
    storageBucket: 'gigafaucet-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB50wwL8wBV0CdrBWbXb14lKz6ncPrHd4',
    appId: '1:645002434672:ios:7570fa5ca0572408a2fcb5',
    messagingSenderId: '645002434672',
    projectId: 'gigafaucet-dev',
    storageBucket: 'gigafaucet-dev.firebasestorage.app',
    iosBundleId: 'com.burgereat.gigafaucet.dev',
  );
}
