name: Deploy Flutter Web to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Build web
        run: |
          flutter clean
          flutter build web --release

      - name: Copy files to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY:  ${{ secrets.EC2_KEY }}
          ROOT: ${{ secrets.WEB_ROOT }}
        run: |
          set -euo pipefail

          mkdir -p ~/.ssh
          echo "$KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

          # Sync build to server
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519" \
            build/web/ "$USER@$HOST:$ROOT/"
          
          # Fix ownership / reload nginx (ignore reload failure if nginx isn't present)
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 "$USER@$HOST" \
            "sudo chown -R www-data:www-data '$ROOT' && sudo systemctl reload nginx || true"